language: objective-c
osx_image: xcode9.3

before_install:
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage

before_script:
  - carthage bootstrap --platform iOS --no-use-binaries --cache-builds
  
script: xcodebuild clean && xcodebuild build -sdk iphonesimulator11.3 -workspace StarterApp.xcworkspace -scheme StarterApp CODE_SIGNING_REQUIRED=NO
