language: objective-c
osx_image: xcode9.2
xcode_workspace: StarterApp.xcworkspace
xcode_scheme: StarterApp

script:
    - xcodebuild clean build -sdk iphonesimulator11.2 -workspace StarterApp.xcworkspace -scheme StarterApp CODE_SIGNING_REQUIRED=NO
